---
- hosts: all
  become: true
  tasks:

    - name: Update repositary index
      dnf:
        name: '*'
        state: latest

    - name: Install apache2 package
      yum:
        name: httpd
        state: latest
