---
- hosts: all
  become: true
  tasks:
  - name: Install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: Install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tags: apache,httpd,centos,ubuntu,apache2
  tasks:
    - name: Install apache and php
      package:
        name:
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: defaults_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mairadb package (Ubuntu)
    tags: db, ubuntu,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:
    - name: install samba (CentOS)
      tags: samba
      dnf:
        name: samba-client
        state: latest
      when: ansible_distribution == "CentOS"
    - name: install samba (Ubuntu)
      tags: samba
      apt:
        name: samba
        state: latest
      when: ansible_distribution == "Ubuntu"
