- name: add sshkey for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6hLoGI6L2kAsCY/LNkyTXsuFWThei4YBsIHsjj/W3Z5p9GLq+A7LrfJeLq5girCnpiiILjfawUhXXzXlJychR4VQhVW/hgooAWjdcI2yMs4mvhSP+M6zhD8zXp1ueG6+nlTqLd/CxqcpnGtxIRUMXdV1REbTiuqmTH0RLyIpOlOhNfQ4jbOMhO1g/hcYp0qVawFA6W9kO6hAJb2mHeAWd9Je97kKuPrTDTUrwoWRg8W6DrS8Bsd6LsJJBc0Oa5RDuApvUztXe4J9Z/7jK+aEZ7yLqV42R4esxIuEQYQNTKPaFVrZGX4hKyhIyjkUH2A1myqkNWeikMoqk+RUGw1tkAbof785qSyJ6nXeu8eazjrH/bbfzM5njqn5XqAN8Vh2wsAGmcv/kciRBuZ1MRxZPi1TTUG/sOzKk8n+2qkF2q6b9QXTu2JO/6Ez7oUCzkNYO7DHRTi4yYFc4i8sLZegzxQCV+jX6iRxVlEabmiusiwiLU1WB+8MRLC2XrwDMNKU= vm@localhost.localdomain"


