- name: Install updates (CentOS)
  tags: always
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "CentOS"
- name: Install update (Ubuntu)
  tags: always
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

